### ISSUE TITLE
Firebase: Error (auth/missing-email)

### ISSUE THREAD

**Issue by xszaryx** [resulturan/refine-firebase#13]
Hi,
I'm starting a new app with refine and I'm trying to connect it to my Firebase. I'm getting an "Firebase: Error (auth/missing-email)" when trying to login in using firebase auth provider. 

![image](https://github.com/resulturan/refine-firebase/assets/39861944/0c194bfa-572e-4b95-beef-2976fbfd1030)

I'm only having Google sign-in provider enable on firebase side.

**Comment by neondeex** [comment]
> Hi, I'm starting a new app with refine and I'm trying to connect it to my Firebase. I'm getting an "Firebase: Error (auth/missing-email)" when trying to login in using firebase auth provider.
> 
> ![image](https://private-user-images.githubusercontent.com/39861944/252627978-0c194bfa-572e-4b95-beef-2976fbfd1030.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NTQyMjgsIm5iZiI6MTcwNTQ1MzkyOCwicGF0aCI6Ii8zOTg2MTk0NC8yNTI2Mjc5NzgtMGMxOTRiZmEtNTcyZS00Yjk1LWJlZWYtMjk3NmZiZmQxMDMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAxMTIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwODQ3NDgwOTk5MmJhZWRlYjgxYWMxZDRmNzkzMGRlZWI0NWY1ZTUwZjY1ZDYyZjBlZDJiYWQwNDc3ODQxODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3yqOlwWaq9MAjqLpvt9RfVyG1X2TzhgJRJNOXUWLx-k)
> 
> I'm only having Google sign-in provider enable on firebase side.

How do you fix?

**Comment by SergiOca87** [comment]
Any fox for this?

**Comment by cpboyd** [comment]
I think part of the issue is that firebaseAuth is currently only supporting `signInWithEmailAndPassword`:
https://github.com/resulturan/refine-firebase/blob/master/src/firebaseAuth.ts#L64

**Comment by resulturan** [comment]
You are right, @cpboyd. I can accept any contributions.
